name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - beta

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: ${{ github.event.inputs.bump_type }}
        PRERELEASE: ${{ github.event.inputs.bump_type == 'beta' }}
        
    - run: |
        echo "Bumped version from ${{ steps.tag.outputs.tag }} to ${{ steps.tag.outputs.new_tag }}"