name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - alpha
          - beta

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get-latest-version.outputs.lastest_version }}
      latest_beta_version: ${{ steps.get-latest-version.outputs.lastest_beta_version }}
      latest_alpha_version: ${{ steps.get-latest-version.outputs.lastest_alpha_version }}
      next_version: ${{ steps.calculate-next-version.outputs.next_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install semver
        run: npm install -g semver

      - name: Get latest version from npm
        id: get-latest-version
        run: |
          echo "lastest_version=$(npm view @joshmiquel/memoryjs version | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "lastest_beta_version=$(npm view @joshmiquel/memoryjs dist-tags.beta | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "lastest_alpha_version=$(npm view @joshmiquel/memoryjs dist-tags.alpha | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Calculate next version with semver
        id: calculate-next-version
        run: |
          if [[ "${{ github.event.inputs.bump_type }}" == "patch" ]]; then
            echo "next_version=$(semver -i patch ${{ steps.get-latest-version.outputs.lastest_version }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.bump_type }}" == "minor" ]]; then
            echo "next_version=$(semver -i minor ${{ steps.get-latest-version.outputs.lastest_version }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.bump_type }}" == "major" ]]; then
            echo "next_version=$(semver -i major ${{ steps.get-latest-version.outputs.lastest_version }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.bump_type }}" == "beta" ]]; then
            echo "next_version=$(semver -i prerelease --preid beta ${{ steps.get-latest-version.outputs.lastest_beta_version || steps.get-latest-version.outputs.lastest_version }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.bump_type }}" == "alpha" ]]; then
            echo "next_version=$(semver -i prerelease --preid alpha ${{ steps.get-latest-version.outputs.lastest_alpha_version || steps.get-latest-version.outputs.lastest_version }})" >> $GITHUB_OUTPUT
          fi
  
  bump-package:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Bump package
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          npm version ${{ inputs.bump_type }} --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version to ${{ needs.prepare.outputs.next_version }}"
          git push

  release-draft:
    needs: [prepare, bump-package]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Notes
        id: generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener versiones
          PREVIOUS_VERSION=${{ needs.prepare.outputs.latest_version }}
          NEXT_VERSION=${{ needs.prepare.outputs.next_version }}
      
          # Generar enlace de comparación
          COMPARE_LINK="https://github.com/${{ github.repository }}/compare/v${PREVIOUS_VERSION}...v${NEXT_VERSION}"
      
          # Obtener PRs merged entre versiones usando la API de GitHub
          PR_LIST=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/pulls?state=closed&sort=updated&direction=desc" \
            --jq '.[] | select(.merged_at and .base.ref == "main") | "- \(.title) by @\(.user.login) in #\(.number)"')
      
          # Filtrar PRs relevantes (puedes ajustar la lógica si necesitas comparar con tags específicos)
          COMMITS=$(echo "$PR_LIST" | head -n 50) # Limita a 50 PRs para evitar exceso
      
          # Obtener nuevos contributors (primera contribución en este rango)
          NEW_CONTRIBUTORS=$(gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/pulls?state=closed" \
            --jq '[.[] | select(.merged_at) | {login: .user.login, number: .number}] | 
                   group_by(.login) | map(select(length == 1)) | .[] | .[0] | 
                   "@\(.login) made their first contribution in #\(.number)"' | sort)
      
          # Crear el body del release
          cat << EOF > release_body.md
          # Release v${NEXT_VERSION}
      
          ## What's Changed
          ${COMMITS}
      
          ## New Contributors
          ${NEW_CONTRIBUTORS}
      
          ## Full Changelog
          ${COMPARE_LINK}
          EOF
        shell: bash

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          draft: true
          prerelease: ${{ inputs.bump_type == 'alpha' || inputs.bump_type == 'beta' }}
          tag_name: v${{ needs.prepare.outputs.next_version }}
          body_path: release_body.md
