name: Publish to npm

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: bun i --frozen-lockfile --ignore-scripts
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install node-gyp
        run: bun add -g node-gyp

      - name: Build
        run: bun run build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Bump version
        run: npm version patch --from-git

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}