name: Publish to npm

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  check-and-publish:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for version check
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install version check dependencies
        working-directory: .github/workflows
        run: npm install

      - name: Check for version change
        id: check
        uses: EndBug/version-check@v2
        with:
          file-url: https://unpkg.com/@joshmiquel/memoryjs/package.json
          static-checking: localIsNew
          
      - name: Validate version
        if: steps.check.outputs.changed == 'true'
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          node .github/workflows/version-check.js "v${CURRENT_VERSION}" "patch"

      - name: Setup Bun
        if: steps.check.outputs.changed == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: bun i --frozen-lockfile --ignore-scripts

      - name: Setup Python
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install node-gyp
        if: steps.check.outputs.changed == 'true'
        run: bun add -g node-gyp

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: bun run build

      - name: Setup Node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type
        run: echo "Version changed and published!"