name: Create Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      description:
        description: 'Release description'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install semver
        run: npm install -g semver

      - name: Update and validate version
        id: version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION=$(npm version ${{ github.event.inputs.type }} --no-git-tag-version)
          node .github/workflows/version-check.js "$NEW_VERSION" "${{ github.event.inputs.type }}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit and tag
        run: |
          git add package.json
          git commit -m "chore: release ${{ steps.version.outputs.new_version }}"
          git tag -a "${{ steps.version.outputs.new_version }}" -m "Release ${{ steps.version.outputs.new_version }}"
          git push
          git push --tags

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          name: Release ${{ steps.version.outputs.new_version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
