name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      # - name: Install GCC
      #   id: install-gcc
      #   uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: build-essential
      #     version: 1.0
      - name: Install build-tools
        run: |
          sudo apt update
          sudo apt install build-essential

      - name: Display installed packages
        run: |
          dpkg -l g++ gcc make build-essential
          
      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node-gyp
        run: npm install -g node-gyp --ignore-scripts

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: bun run build

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: memoryjs
      #     path: lib/
  
  # release:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.inputs.checkout-branch }}
  #         submodules: true

  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4.1.7
  #       with:
  #         name: memoryjs
  #         path: lib/

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         registry-url: 'https://registry.npmjs.org'
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  #     - name: Publish release
  #       run: npm publish --access public